#!/usr/bin/env bash
# Builds the three shippable forms out of src/. No dependencies, no minifier.
set -euo pipefail

cd "$(dirname "$0")"
mkdir -p dist

PHYSICS=src/physics.js
GAME=src/game.js

# --- 1. console bundle: paste into devtools; also the body of the bookmarklet --
{
  echo "/* moto-charts bundle — generated by build.sh, do not edit. Source: src/ */"
  cat "$PHYSICS"
  cat "$GAME"
  echo "MotoCharts.start();"
} > dist/moto.bundle.js

# --- 2. bookmarklet ----------------------------------------------------------
# Everything inline: a <script src> would be blocked by the page's CSP, while a
# javascript: bookmarklet runs with the page's own privileges.
node -e '
const fs = require("fs");
const body = fs.readFileSync("dist/moto.bundle.js", "utf8");
const wrapped = "(function(){" + body + "})();";
fs.writeFileSync("dist/bookmarklet.txt", "javascript:" + encodeURIComponent(wrapped) + "\n");
'

# --- 3. browser extension, one tree per browser ------------------------------
# Same code both times; only the manifest differs (Firefox MV3 wants background
# scripts, Chrome MV3 wants a service worker).
build_extension() {
  local browser="$1" out="dist/extension-$1"
  rm -rf "$out"
  mkdir -p "$out/content" "$out/icons"
  cp extension/launcher.js extension/background.js extension/popup.html extension/popup.js "$out/"
  cp extension/icons/*.png "$out/icons/"
  cp "$PHYSICS" "$GAME" "$out/content/"
  cp "extension/manifest.$browser.json" "$out/manifest.json"
}

build_extension firefox
build_extension chrome

# .xpi is a plain zip; -X keeps macOS resource forks out of it
( cd dist/extension-firefox && zip -qrX ../moto-charts.xpi . )
( cd dist/extension-chrome  && zip -qrX ../moto-charts-chrome.zip . )

printf "built:\n"
for f in dist/moto-charts.xpi dist/moto-charts-chrome.zip \
         dist/moto.bundle.js dist/bookmarklet.txt; do
  printf "  %-30s %6s KB\n" "$f" "$(( $(wc -c < "$f") / 1024 ))"
done
printf "  %-30s %6s\n" "dist/extension-firefox/" "(unpacked — for about:debugging)"
printf "  %-30s %6s\n" "dist/extension-chrome/" "(unpacked — for chrome://extensions)"
